# Generated by Django 4.0.6 on 2022-07-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
            ],
        ),
    ]
