# Generated by Django 4.0.6 on 2022-08-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_employees_delete_user_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicament', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('id_request', models.IntegerField(default=0)),
            ],
        ),
    ]
