# Generated by Django 4.0.6 on 2022-08-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='senha',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='cpf',
            new_name='id',
        ),
    ]
