# Generated by Django 4.0.6 on 2022-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='quant',
            field=models.IntegerField(default=0),
        ),
    ]
